package tt.com;
// Generated Jan 10, 2020 9:06:32 AM by Hibernate Tools 4.3.1



/**
 * Cus generated by hbm2java
 */
public class Cus  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String password;
     private String address;
     private Integer payment;

    public Cus() {
    }

    public Cus(String name, String email, String password, String address, Integer payment) {
       this.name = name;
       this.email = email;
       this.password = password;
       this.address = address;
       this.payment = payment;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getPayment() {
        return this.payment;
    }
    
    public void setPayment(Integer payment) {
        this.payment = payment;
    }




}


