package tt.com;
// Generated Jan 10, 2020 9:06:32 AM by Hibernate Tools 4.3.1



/**
 * Pro generated by hbm2java
 */
public class Pro  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String epectDate;
     private Integer price;
     private Integer discount;

    public Pro() {
    }

    public Pro(String name, String epectDate, Integer price, Integer discount) {
       this.name = name;
       this.epectDate = epectDate;
       this.price = price;
       this.discount = discount;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEpectDate() {
        return this.epectDate;
    }
    
    public void setEpectDate(String epectDate) {
        this.epectDate = epectDate;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Integer getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }




}


